{"version":3,"sources":["components/ConferenceCallAlert/i18n/de-DE.js"],"names":["conferenceCallErrors","bringInFailed","makeConferenceFailed","terminateConferenceFailed","removeFromConferenceFailed"],"mappings":";;;;;;;;;;;;AAAA;;;;;;oGAGGA,+BAAqBC,a,EAAgB,oH,wDACrCD,+BAAqBE,oB,EAAuB,oH,wDAC5CF,+BAAqBG,yB,EAA4B,kH,wDACjDH,+BAAqBI,0B,EAA6B,sH;;AAGrD;AACA;AACA;AACA","file":"de-DE.js","sourcesContent":["import conferenceCallErrors from 'ringcentral-integration/modules/ConferenceCall/conferenceCallErrors';\n\nexport default {\n  [conferenceCallErrors.bringInFailed]: \"Das Zusammenführen von Anrufen ist wegen unerwarteter Fehler fehlgeschlagen. Bitte versuchen Sie es später erneut.\",\n  [conferenceCallErrors.makeConferenceFailed]: \"Das Zusammenführen von Anrufen ist wegen unerwarteter Fehler fehlgeschlagen. Bitte versuchen Sie es später erneut.\",\n  [conferenceCallErrors.terminateConferenceFailed]: \"Das Beenden der Konferenz ist aufgrund unerwarteter Fehler fehlgeschlagen. Bitte versuchen Sie es später erneut.\",\n  [conferenceCallErrors.removeFromConferenceFailed]: \"Das Entfernen des Teilnehmers ist aufgrund unerwarteter Fehler fehlgeschlagen. Bitte versuchen Sie es später erneut.\"\n};\n\n// @key: @#@\"[conferenceCallErrors.bringInFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.makeConferenceFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.terminateConferenceFailed]\"@#@ @source: @#@\"Failed to hangup the conference due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.removeFromConferenceFailed]\"@#@ @source: @#@\"Failed to remove the participant due to unexpected errors. Please try again later.\"@#@\n"]}