{"version":3,"sources":["components/ConferenceCallAlert/i18n/en-US.js"],"names":["conferenceCallErrors","bringInFailed","makeConferenceFailed","terminateConferenceFailed","removeFromConferenceFailed"],"mappings":";;;;;;;;;;;;AAAA;;;;;;oGAGGA,+BAAqBC,a,EAAgB,6E,wDACrCD,+BAAqBE,oB,EAAuB,6E,wDAC5CF,+BAAqBG,yB,EAA4B,mF,wDACjDH,+BAAqBI,0B,EAA6B,oF","file":"en-US.js","sourcesContent":["import conferenceCallErrors from 'ringcentral-integration/modules/ConferenceCall/conferenceCallErrors';\n\nexport default {\n  [conferenceCallErrors.bringInFailed]: 'Failed to merge the calls due to unexpected errors. Please try again later.',\n  [conferenceCallErrors.makeConferenceFailed]: 'Failed to merge the calls due to unexpected errors. Please try again later.',\n  [conferenceCallErrors.terminateConferenceFailed]: 'Failed to hangup the conference due to unexpected errors. Please try again later.',\n  [conferenceCallErrors.removeFromConferenceFailed]: 'Failed to remove the participant due to unexpected errors. Please try again later.',\n};\n"]}