{"version":3,"sources":["components/ConferenceCallAlert/i18n/fr-FR.js"],"names":["conferenceCallErrors","bringInFailed","makeConferenceFailed","terminateConferenceFailed","removeFromConferenceFailed"],"mappings":";;;;;;;;;;;;AAAA;;;;;;oGAGGA,+BAAqBC,a,EAAgB,mG,wDACrCD,+BAAqBE,oB,EAAuB,mG,wDAC5CF,+BAAqBG,yB,EAA4B,0G,wDACjDH,+BAAqBI,0B,EAA6B,4G;;AAGrD;AACA;AACA;AACA","file":"fr-FR.js","sourcesContent":["import conferenceCallErrors from 'ringcentral-integration/modules/ConferenceCall/conferenceCallErrors';\n\nexport default {\n  [conferenceCallErrors.bringInFailed]: \"Échec de la fusion des appels en raison d'erreurs inattendues. Veuillez réessayer ultérieurement.\",\n  [conferenceCallErrors.makeConferenceFailed]: \"Échec de la fusion des appels en raison d'erreurs inattendues. Veuillez réessayer ultérieurement.\",\n  [conferenceCallErrors.terminateConferenceFailed]: \"Échec de la clôture de la conférence en raison d'erreurs inattendues. Veuillez réessayer ultérieurement.\",\n  [conferenceCallErrors.removeFromConferenceFailed]: \"Échec de la suppression du participant en raison d'erreurs inattendues. Veuillez réessayer ultérieurement.\"\n};\n\n// @key: @#@\"[conferenceCallErrors.bringInFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.makeConferenceFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.terminateConferenceFailed]\"@#@ @source: @#@\"Failed to hangup the conference due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.removeFromConferenceFailed]\"@#@ @source: @#@\"Failed to remove the participant due to unexpected errors. Please try again later.\"@#@\n"]}