{"version":3,"sources":["components/ConferenceCallAlert/i18n/ja-JP.js"],"names":["conferenceCallErrors","bringInFailed","makeConferenceFailed","terminateConferenceFailed","removeFromConferenceFailed"],"mappings":";;;;;;;;;;;;AAAA;;;;;;oGAGGA,+BAAqBC,a,EAAgB,6C,wDACrCD,+BAAqBE,oB,EAAuB,6C,wDAC5CF,+BAAqBG,yB,EAA4B,4C,wDACjDH,+BAAqBI,0B,EAA6B,6C;;AAGrD;AACA;AACA;AACA","file":"ja-JP.js","sourcesContent":["import conferenceCallErrors from 'ringcentral-integration/modules/ConferenceCall/conferenceCallErrors';\n\nexport default {\n  [conferenceCallErrors.bringInFailed]: \"予期しないエラーにより、通話をマージできませんでした。後でもう一度やり直してください。\",\n  [conferenceCallErrors.makeConferenceFailed]: \"予期しないエラーにより、通話をマージできませんでした。後でもう一度やり直してください。\",\n  [conferenceCallErrors.terminateConferenceFailed]: \"予期しないエラーにより、会議を終了できませんでした。後でもう一度やり直してください。\",\n  [conferenceCallErrors.removeFromConferenceFailed]: \"予期しないエラーにより、参加者を削除できませんでした。後でもう一度やり直してください。\"\n};\n\n// @key: @#@\"[conferenceCallErrors.bringInFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.makeConferenceFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.terminateConferenceFailed]\"@#@ @source: @#@\"Failed to hangup the conference due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.removeFromConferenceFailed]\"@#@ @source: @#@\"Failed to remove the participant due to unexpected errors. Please try again later.\"@#@\n"]}