{"version":3,"sources":["components/ConferenceCallAlert/i18n/zh-CN.js"],"names":["conferenceCallErrors","bringInFailed","makeConferenceFailed","terminateConferenceFailed","removeFromConferenceFailed"],"mappings":";;;;;;;;;;;;AAAA;;;;;;oGAGGA,+BAAqBC,a,EAAgB,sB,wDACrCD,+BAAqBE,oB,EAAuB,sB,wDAC5CF,+BAAqBG,yB,EAA4B,sB,wDACjDH,+BAAqBI,0B,EAA6B,uB;;AAGrD;AACA;AACA;AACA","file":"zh-CN.js","sourcesContent":["import conferenceCallErrors from 'ringcentral-integration/modules/ConferenceCall/conferenceCallErrors';\n\nexport default {\n  [conferenceCallErrors.bringInFailed]: \"由于意外错误，合并通话失败。请稍后重试。\",\n  [conferenceCallErrors.makeConferenceFailed]: \"由于意外错误，合并通话失败。请稍后重试。\",\n  [conferenceCallErrors.terminateConferenceFailed]: \"由于意外错误，挂断会议失败。请稍后重试。\",\n  [conferenceCallErrors.removeFromConferenceFailed]: \"由于意外错误，移除参与者失败。请稍后重试。\"\n};\n\n// @key: @#@\"[conferenceCallErrors.bringInFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.makeConferenceFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.terminateConferenceFailed]\"@#@ @source: @#@\"Failed to hangup the conference due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.removeFromConferenceFailed]\"@#@ @source: @#@\"Failed to remove the participant due to unexpected errors. Please try again later.\"@#@\n"]}